# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locate_model_yelp',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='locate_model_yelp',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='locate_model_yelp',
            name='name',
        ),
        migrations.AlterField(
            model_name='locate_model_yelp',
            name='zip_code',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
