# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc_api', '0002_auto_20171226_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='locate_model_yelp',
            name='save_flag',
            field=models.BooleanField(default=False),
        ),
    ]
