# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc_api', '0003_locate_model_yelp_save_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locate_model_yelp',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
