# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc_api', '0004_auto_20171227_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='locate_model_yelp',
            name='foursquare',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locate_model_yelp',
            name='venue',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='locate_model_yelp',
            name='yelp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
