# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loc_api', '0005_auto_20171227_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locate_model_yelp',
            old_name='foursquare',
            new_name='api_used',
        ),
        migrations.RemoveField(
            model_name='locate_model_yelp',
            name='yelp',
        ),
    ]
